name: Python CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          activate-environment: 'foo'
      - name: Install dependencies
        run: |
          conda install pip
          pip install -r requirements-dev.txt
      - name: Build with maturin
        run: |
          maturin develop --release
      - name: Lint with flake8
        run: |
          python -m flake8 python tests
        continue-on-error: true
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: "4.4"
          mongodb-replica-set: rs1
          mongodb-port: 27117
      - name: Run tests
        # run: python -m pytest tests
        # run: python -m pytest tests --cov=./python/mongojet --cov-report term-missing -s
        run: python -m pytest tests --cov=./python/mongojet --cov-report xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: romis2012/mongojet
          file: ./coverage.xml
          flags: unit
          fail_ci_if_error: false